### PR TITLE
STYLE: Reformat Python code with `black`

### PR DESCRIPTION
**Pull request by Leengit**
Implemented with
```shell
find . -name "*.py" -print0 | xargs -0 black
```
Manually wrap comment text to 88 characters too.

### CODE REVIEW

**Comment by Leengit** [comment]
> ... I suggest to install follow up on the work initiated ...

Is it reasonable to defer this to a different pull request?

**Review by ebrahimebrahim — COMMENTED** [review]
I don't like that it changed 2-space indentation to 4-space. Is that something you can configure?

Regarding JC's comment, I don't have any preference about whether this is a one-time reformatting or whether it's included in github actions. The flake8 thing that JC added is already  pretty good.

**Comment by Leengit** [comment]
> I don't like that it changed 2-space indentation to 4-space. Is that something you can configure?

I don't like that it uses a line length of 88 instead of something like 120 that I find much more reasonable.  Yes, these things are configurable.  However, the argument usually goes that we should accept the `black` defaults so that it looks like other people's code.

**Comment by ebrahimebrahim** [comment]
Yeah I agree also 88 seems really small.
Line length 120 sounds good!

**Comment by jcfr** [comment]
Considering there is already infrastructure to address styling, I suggest to update it. Looking at the changes we introduced in upstream Slicer (e.g see [here](https://github.com/Slicer/Slicer/commits/main/.flake8), [here](https://github.com/Slicer/Slicer/blob/main/.git-blame-ignore-revs) and [here](https://github.com/Slicer/Slicer/commits/main/.pre-commit-config.yaml)) may be helpful.

Generally speaking, once styling change are integrated, the file [.git-blame-ignore-revs](https://github.com/Slicer/Slicer/blob/main/.git-blame-ignore-revs) should be updated to ensure `git blame` (either from command line or from within GitHub UI) ignore these and allows to follow the history independently of style changes.

That said, in the future, adopting `black` is definitely possible. I would recommend to gradually converge to it instead of applying this huge set of changes.

For example, like we have done in Slicer, updating the `.flake8` configuration removing exception and addressing them would be a good first step.

**Comment by ebrahimebrahim** [comment]
> That said, in the future, adopting `black` is definitely possible. I would recommend to gradually converge to it instead of applying this huge set of changes.
> 
> For example, like we have done in Slicer, updating the `.flake8` configuration removing exception and addressing them would be a good first step.

I think I agree with this.

@Leengit Instead of the one big static style update, would you want to look into removing some of the flake8 exceptions for the aspects of style that could be improved? Or if this is becoming too much trouble to be worth it for you then feel free to close the PR? I just think that it's much better when sweeping style changes occur via the linting configuration

> Generally speaking, once styling change are integrated, the file [.git-blame-ignore-revs](https://github.com/Slicer/Slicer/blob/main/.git-blame-ignore-revs) should be updated to ensure `git blame` (either from command line or from within GitHub UI) ignore these and allows to follow the history independently of style changes.

ah thank you I was wondering how the blame ignoring worked!

**Comment by jcfr** [comment]
> was wondering how the blame ignoring worked

And to illustrate, see https://github.com/Slicer/Slicer/pull/6306#issuecomment-1092426901

**Comment by Leengit** [comment]
I prefer automated approaches such as `black`.  I find that easier to implement than addressing `flake8` exceptions and that it provides more consistency in the code.  Would it help if we go for `black` with a line length of 120 and an indent of 2?  We can then proceed to install hooks to automate formatting on every commit, so that no one need think about this much going forward -- at least in theory; I haven't actually done this before, though ITK does something similar with clang-format of C++ code.)

**Comment by ebrahimebrahim** [comment]
> Would it help if we go for `black` with a line length of 120 and an indent of 2?

I'm okay with it as a one time adjustment

I don't mind running flake8 corrections locally and it is kind of nice to have full control over what gets commited, so I think I ultimately prefer the approach of managing code style enforcement via flake8 config, with no automated formatting

**Comment by Leengit** [comment]
I have just pushed a version of the code formatted with `find . -name "*.py" -print0 | xargs -0 black -l 120 -C`.  That sets line length to 120 instead of the default of 88.  Also `-C` says to put each list on one line if it fits, even when the last list entry has a trailing comma (which is usually the signal to `black` for "don't collapse to one line").  I could not find a way to override the indentation from 4 spaces to 2 spaces.  Thoughts ... merge, change, or close?

**Comment by ebrahimebrahim** [comment]
Thanks, I guess I can live with 4 spaces :slightly_smiling_face: 

Good to merge :+1:

**Comment by jcfr** [comment]
Transitioning to 4 spaces makes sense, could this be done in a first PR ? Then move forward with the other updates.

**Comment by jcfr** [comment]
See here to find out which comment to run:
https://github.com/Slicer/Slicer/commit/9390be6bf76e048e6fd384d8bfd607eba2857b5a

**Review by jcfr — COMMENTED** [review]
I suggest to first move forward with https://github.com/KitwareMedical/lungair-desktop-application/pull/52

**Comment by Leengit** [comment]
With this latest force-push I hacked the `black` source code so that it uses 2-space indents.  I also squashed this series of commits into a single commit.  Once Pull Request #52 is merged, I can update this pull request again -- or submit a new pull request if this one has already been merged.

**Comment by Leengit** [comment]
I just saw @jcfr comment about transitioning to 4-space indents first.  Unfortunately, `black` won't do just that, so we'd have to manage that some other way.  The philosophy about `black` is to be opinionated and not flexible.  That gets uniformity in the code, but perhaps not the same format as we have aimed for in the past.  `black` is mighty convenient, which is why I favor it, but if we go with an alternative then we can simply close this pull request without merging.

**Comment by jcfr** [comment]
Since the current infrastructure used flake8 et alike, changes should be done considering the existing infrastructure. For now, I suggest to close this pull request and move forward with #52, the proposed changes are aligned with `black` style and a step in the "right" direction.

> Once Pull Request https://github.com/KitwareMedical/lungair-desktop-application/pull/52 is merged, I can update this pull request again -- or submit a new pull request if this one has already been merged.

For now, this pull request could be closed, and eventually re-opened afterward.

**Pull request closed without merging**
